AWSTemplateFormatVersion: "2021-02-16"
Description: Template for automated stacks tests
Parameters:
  InstanceSecurityGroup:
    Description: An environment name that is prefixed to resource names
    Type: String
    
  AMI:
    Description: An environment name that is prefixed to resource names
    Type: String
    
  InstanceType:
    Description: An environment name that is prefixed to resource names
    Type: String

    
  KeyName:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:
            
    StackEC2Instance: #An inline comment
        Type: "AWS::EC2::Instance"
        Properties: 
          ImageId: !Ref AMI
          InstanceType: !Ref InstanceType
          KeyName: !Ref KeyName
          SubnetId: !Ref PublicSubnet1
          SecurityGroupIds: !Ref InstanceSecurityGroup
          UserData: 
            Fn::Base64:
                !Sub |
                  #!/bin/bash -xe
                  sudo apt update
                  sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
                  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
                  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
                  sudo apt update
                  apt-cache policy docker-ce
                  sudo apt install -y docker-ce
                  sudo usermod -aG docker ubuntu
          
    DPAEC2Instance: #An inline comment
        Type: "AWS::EC2::Instance"
        Properties: 
          ImageId: !Ref AMI
          InstanceType: !Ref InstanceType
          KeyName: !Ref KeyName
          SubnetId: !Ref PublicSubnet1
          SecurityGroupIds: !Ref InstanceSecurityGroup
          UserData: 
            Fn::Base64:
                !Sub |
                  #!/bin/bash -xe
                  sudo apt update
                  sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
                  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
                  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
                  sudo apt update
                  apt-cache policy docker-ce
                  sudo apt install -y docker-ce
                  sudo usermod -aG docker ubuntu
          
Outputs:
  StackInstanceID:
    Description: The Stack Instance ID 
    Value: !Ref StackEC2Instance
    
  DPAInstanceID:
    Description: The Stack Instance ID 
    Value: !Ref DPAEC2Instance